---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Event-RPC
no_index:
  directory:
    - t
    - inc
requires:
  CBOR::XS: '0'
  Event: '0'
  Glib: '0'
  IO::Socket::INET: '0'
  IO::Socket::SSL: '0'
  JSON::XS: '3'
  Net::SSLeay: '0'
  Sereal: '3'
  Storable: '0'
  Test::More: '0'
version: '1.08'
