--- #YAML:1.0
name:               Event-RPC
version:            1.03
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Event:             0
    Glib:              0
    IO::Socket::INET:  0
    IO::Socket::SSL:   0
    Net::SSLeay:       0
    Storable:          0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
